apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: twitter-advanced-search-cronjob
  namespace: test2
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  schedule: "@hourly"
  successfulJobsHistoryLimit: 10
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: twitter-advanced-search-cronjob
    spec:
      parallelism: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: Never
          containers:
          - name: twitter-advanced-search-cronjob
            image: ${DOCKER_REGISTRY}/covid-parser:${CI_COMMIT_SHA}
            command: [ "python3.6", "-u", "job_task.py" ]
            env:
            - name: RABBITMQ_HOST
              value: ${RABBITMQ_HOST}
            - name: RABBITMQ_PORT
              value: '${RABBITMQ_PORT}'
            - name: RABBITMQ_QUEUE
              value: ${RABBITMQ_QUEUE}
            - name: RABBITMQ_USER
              value: ${RABBITMQ_USER}
            - name: RABBITMQ_PASSWORD
              value: ${RABBITMQ_PASSWORD}
            - name: MONGODB_HOST
              value: ${MONGODB_HOST}
            - name: MONGODB_PORT
              value: '${MONGODB_PORT}'
            - name: MONGODB_DB
              value: ${MONGODB_DB}
            - name: MONGODB_TASK_COLLECTION
              value: ${MONGODB_TASK_COLLECTION}
            - name: MONGODB_RESULT_COLLECTION
              value: ${MONGODB_RESULT_COLLECTION}
            - name: MONGODB_USER
              value: ${MONGODB_USER}
            - name: MONGODB_PASSWORD
              value: ${MONGODB_PASSWORD}
            - name: MONGODB_AUTH_DB
              value: ${MONGODB_AUTH_DB}
            - name: PROXIES_FILE_PATH_OR_URL
              value: ${PROXIES_FILE_PATH_OR_URL}
            - name: PROXIES_TYPE
              value: ${PROXIES_TYPE}
            volumeMounts:
            - mountPath: ${MOUNT_CONTAINER_PATH}
              name: proxies-mount
          volumes:
          - name: proxies-mount
            hostPath:
              path: ${MOUNT_HOST_PATH}
              type: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-advanced-search-consumer
  namespace: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: twitter-advanced-search-consumer
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: twitter-advanced-search-consumer
    spec:
      containers:
      - args:
        - python3.6
        - -u
        - consumer-twitter-advanced-search_api.py
        image: ${DOCKER_REGISTRY}/covid-parser:${CI_COMMIT_SHA}
        imagePullPolicy: Always
        name: twitter-advanced-search-consumer
        env:
          - name: RABBITMQ_HOST
            value: ${RABBITMQ_HOST}
          - name: RABBITMQ_PORT
            value: '${RABBITMQ_PORT}'
          - name: RABBITMQ_QUEUE
            value: ${RABBITMQ_QUEUE}
          - name: RABBITMQ_USER
            value: ${RABBITMQ_USER}
          - name: RABBITMQ_PASSWORD
            value: ${RABBITMQ_PASSWORD}
          - name: MONGODB_HOST
            value: ${MONGODB_HOST}
          - name: MONGODB_PORT
            value: '${MONGODB_PORT}'
          - name: MONGODB_DB
            value: ${MONGODB_DB}
          - name: MONGODB_TASK_COLLECTION
            value: ${MONGODB_TASK_COLLECTION}
          - name: MONGODB_RESULT_COLLECTION
            value: ${MONGODB_RESULT_COLLECTION}
          - name: MONGODB_USER
            value: ${MONGODB_USER}
          - name: MONGODB_PASSWORD
            value: ${MONGODB_PASSWORD}
          - name: MONGODB_AUTH_DB
            value: ${MONGODB_AUTH_DB}
          - name: PROXIES_FILE_PATH_OR_URL
            value: ${PROXIES_FILE_PATH_OR_URL}
          - name: PROXIES_TYPE
            value: ${PROXIES_TYPE}
        volumeMounts:
        - mountPath: ${MOUNT_CONTAINER_PATH}
          name: proxies-mount
      volumes:
      - name: proxies-mount
        hostPath:
          path: ${MOUNT_HOST_PATH}
          type: ""